### ISSUE TITLE
Release 1.2.1 is gone

### ISSUE THREAD

**Issue by pallxk** [nsqio/helm-chart#6]
I understand that we're decoupling chart version from app version. But chart version 1.2.1 is still listed in https://github.com/nsqio/helm-chart/blob/gh-pages/index.yaml#L24-L26, while the release has been deleted.

This breaks existing deployment script which uses chart version 1.2.1, and breaks new users running `helm install my-release nsqio/nsq` as well as 1.2.1 is newer than 0.0.2 and will be used by default.

```
$ helm repo add nsqio https://nsqio.github.io/helm-chart
"nsqio" has been added to your repositories
$ helm install my-release nsqio/nsq
Error: INSTALLATION FAILED: failed to download "nsqio/nsq"
```

**Comment by ploxiln** [comment]
Hi, sorry about this, we don't really use helm ...

What I think happened is that, after a correction to the chart was merged, it was realized that the chart version should be different than the application version, so that was done in https://github.com/nsqio/helm-chart/commit/66252d4dfac6646f68ea46d2ccd65680369ab5fc and then it was noticed that the new release was not the latest release, so the 1.2.1 release was deleted, but the index created by the github action remained with 1.2.1 as the latest chart version.

So I guess one way to fix this is to delete the 1.2.1 tag in this repo, push up a bump to 0.0.3, and hope that the github action generates the index as desired now. Another way would be to manually edit https://github.com/nsqio/helm-chart/blob/gh-pages/index.yaml to remove the unintended and now broken 1.2.1 chart version. I think I'll go ahead and try the former strategy first, and if that fails fall back to the second.

cc @mreiferson

**Comment by ploxiln** [comment]
First strategy was not sufficient, the 0.0.3 release was simply added to the index, and the now-fully-removed 1.2.1 chart version was not removed from the index. So I just went ahead and manually removed it from the index. A `helm repo update` and `helm search repo -l` shows that it seems to have done the trick.

So that was clearly rather unfortunate for versioning of releases of anything, I can only fall back on the excuse that this chart, and our familiarity of helm, is in its infancy, and I expect that the versions will be monotonically increasing from here on out :)

**Comment by ploxiln** [comment]
(... and yes I realize that, while this fixes things for those newly installing the chart, it doesn't fix things for those who had pinned the 1.2.1 version of the chart in their deployment system ... I dunno if we want to jump right back up to version 1.2.1, maybe we do I guess, but maybe there will be some understanding since that was the very first version of this chart ever published ...)

**Comment by mreiferson** [comment]
@pallxk sorry, this one's on me, but I agree with the actions @ploxiln took to "fix" this. I don't think we should re-publish 1.2.1 — anyone with automation depending on this can easily correct the issue (but of course we commit to not doing this ever again).

**Comment by pallxk** [comment]
Sorry for not getting back on the issues in time. You've done a great job with the helm chart for nsq, making it much easier for helm users to deploy it. And I appreciated your help on the issues, thanks!

And I'm also okay with not republishing 1.2.1, which can make it clear for new comers that chart version is separate and independent from nsq version.

Regrads.
